# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/developer/git/aecs4u.it/calculix.BAK/NASTRAN-95

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/developer/git/aecs4u.it/calculix.BAK/NASTRAN-95

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/developer/git/aecs4u.it/calculix.BAK/NASTRAN-95/CMakeFiles /mnt/developer/git/aecs4u.it/calculix.BAK/NASTRAN-95//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/developer/git/aecs4u.it/calculix.BAK/NASTRAN-95/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nastran_common

# Build rule for target.
nastran_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_common
.PHONY : nastran_common

# fast build rule for target.
nastran_common/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/nastran_common.dir/build.make src/common/CMakeFiles/nastran_common.dir/build
.PHONY : nastran_common/fast

#=============================================================================
# Target rules for targets named nastran_io

# Build rule for target.
nastran_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_io
.PHONY : nastran_io

# fast build rule for target.
nastran_io/fast:
	$(MAKE) $(MAKESILENT) -f src/system/CMakeFiles/nastran_io.dir/build.make src/system/CMakeFiles/nastran_io.dir/build
.PHONY : nastran_io/fast

#=============================================================================
# Target rules for targets named nastran_database

# Build rule for target.
nastran_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_database
.PHONY : nastran_database

# fast build rule for target.
nastran_database/fast:
	$(MAKE) $(MAKESILENT) -f src/system/CMakeFiles/nastran_database.dir/build.make src/system/CMakeFiles/nastran_database.dir/build
.PHONY : nastran_database/fast

#=============================================================================
# Target rules for targets named nastran_platform

# Build rule for target.
nastran_platform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_platform
.PHONY : nastran_platform

# fast build rule for target.
nastran_platform/fast:
	$(MAKE) $(MAKESILENT) -f src/system/CMakeFiles/nastran_platform.dir/build.make src/system/CMakeFiles/nastran_platform.dir/build
.PHONY : nastran_platform/fast

#=============================================================================
# Target rules for targets named nastran_algorithms

# Build rule for target.
nastran_algorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_algorithms
.PHONY : nastran_algorithms

# fast build rule for target.
nastran_algorithms/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/nastran_algorithms.dir/build.make src/core/CMakeFiles/nastran_algorithms.dir/build
.PHONY : nastran_algorithms/fast

#=============================================================================
# Target rules for targets named nastran_matrices

# Build rule for target.
nastran_matrices: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_matrices
.PHONY : nastran_matrices

# fast build rule for target.
nastran_matrices/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/nastran_matrices.dir/build.make src/core/CMakeFiles/nastran_matrices.dir/build
.PHONY : nastran_matrices/fast

#=============================================================================
# Target rules for targets named nastran_core_solvers

# Build rule for target.
nastran_core_solvers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_core_solvers
.PHONY : nastran_core_solvers

# fast build rule for target.
nastran_core_solvers/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/nastran_core_solvers.dir/build.make src/core/CMakeFiles/nastran_core_solvers.dir/build
.PHONY : nastran_core_solvers/fast

#=============================================================================
# Target rules for targets named nastran_elements_beam

# Build rule for target.
nastran_elements_beam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_elements_beam
.PHONY : nastran_elements_beam

# fast build rule for target.
nastran_elements_beam/fast:
	$(MAKE) $(MAKESILENT) -f src/elements/CMakeFiles/nastran_elements_beam.dir/build.make src/elements/CMakeFiles/nastran_elements_beam.dir/build
.PHONY : nastran_elements_beam/fast

#=============================================================================
# Target rules for targets named nastran_elements_shell

# Build rule for target.
nastran_elements_shell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_elements_shell
.PHONY : nastran_elements_shell

# fast build rule for target.
nastran_elements_shell/fast:
	$(MAKE) $(MAKESILENT) -f src/elements/CMakeFiles/nastran_elements_shell.dir/build.make src/elements/CMakeFiles/nastran_elements_shell.dir/build
.PHONY : nastran_elements_shell/fast

#=============================================================================
# Target rules for targets named nastran_elements_solid

# Build rule for target.
nastran_elements_solid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_elements_solid
.PHONY : nastran_elements_solid

# fast build rule for target.
nastran_elements_solid/fast:
	$(MAKE) $(MAKESILENT) -f src/elements/CMakeFiles/nastran_elements_solid.dir/build.make src/elements/CMakeFiles/nastran_elements_solid.dir/build
.PHONY : nastran_elements_solid/fast

#=============================================================================
# Target rules for targets named nastran_elements_aero

# Build rule for target.
nastran_elements_aero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_elements_aero
.PHONY : nastran_elements_aero

# fast build rule for target.
nastran_elements_aero/fast:
	$(MAKE) $(MAKESILENT) -f src/elements/CMakeFiles/nastran_elements_aero.dir/build.make src/elements/CMakeFiles/nastran_elements_aero.dir/build
.PHONY : nastran_elements_aero/fast

#=============================================================================
# Target rules for targets named nastran_solvers_backends

# Build rule for target.
nastran_solvers_backends: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_solvers_backends
.PHONY : nastran_solvers_backends

# fast build rule for target.
nastran_solvers_backends/fast:
	$(MAKE) $(MAKESILENT) -f src/solvers/CMakeFiles/nastran_solvers_backends.dir/build.make src/solvers/CMakeFiles/nastran_solvers_backends.dir/build
.PHONY : nastran_solvers_backends/fast

#=============================================================================
# Target rules for targets named nastran_analysis_static

# Build rule for target.
nastran_analysis_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_analysis_static
.PHONY : nastran_analysis_static

# fast build rule for target.
nastran_analysis_static/fast:
	$(MAKE) $(MAKESILENT) -f src/analysis/CMakeFiles/nastran_analysis_static.dir/build.make src/analysis/CMakeFiles/nastran_analysis_static.dir/build
.PHONY : nastran_analysis_static/fast

#=============================================================================
# Target rules for targets named nastran_analysis_dynamic

# Build rule for target.
nastran_analysis_dynamic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_analysis_dynamic
.PHONY : nastran_analysis_dynamic

# fast build rule for target.
nastran_analysis_dynamic/fast:
	$(MAKE) $(MAKESILENT) -f src/analysis/CMakeFiles/nastran_analysis_dynamic.dir/build.make src/analysis/CMakeFiles/nastran_analysis_dynamic.dir/build
.PHONY : nastran_analysis_dynamic/fast

#=============================================================================
# Target rules for targets named nastran_analysis_modal

# Build rule for target.
nastran_analysis_modal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_analysis_modal
.PHONY : nastran_analysis_modal

# fast build rule for target.
nastran_analysis_modal/fast:
	$(MAKE) $(MAKESILENT) -f src/analysis/CMakeFiles/nastran_analysis_modal.dir/build.make src/analysis/CMakeFiles/nastran_analysis_modal.dir/build
.PHONY : nastran_analysis_modal/fast

#=============================================================================
# Target rules for targets named nastran_parser

# Build rule for target.
nastran_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_parser
.PHONY : nastran_parser

# fast build rule for target.
nastran_parser/fast:
	$(MAKE) $(MAKESILENT) -f src/utilities/CMakeFiles/nastran_parser.dir/build.make src/utilities/CMakeFiles/nastran_parser.dir/build
.PHONY : nastran_parser/fast

#=============================================================================
# Target rules for targets named nastran_output

# Build rule for target.
nastran_output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_output
.PHONY : nastran_output

# fast build rule for target.
nastran_output/fast:
	$(MAKE) $(MAKESILENT) -f src/utilities/CMakeFiles/nastran_output.dir/build.make src/utilities/CMakeFiles/nastran_output.dir/build
.PHONY : nastran_output/fast

#=============================================================================
# Target rules for targets named nastran_helpers

# Build rule for target.
nastran_helpers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_helpers
.PHONY : nastran_helpers

# fast build rule for target.
nastran_helpers/fast:
	$(MAKE) $(MAKESILENT) -f src/utilities/CMakeFiles/nastran_helpers.dir/build.make src/utilities/CMakeFiles/nastran_helpers.dir/build
.PHONY : nastran_helpers/fast

#=============================================================================
# Target rules for targets named nastran_blockdata

# Build rule for target.
nastran_blockdata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_blockdata
.PHONY : nastran_blockdata

# fast build rule for target.
nastran_blockdata/fast:
	$(MAKE) $(MAKESILENT) -f src/blockdata/CMakeFiles/nastran_blockdata.dir/build.make src/blockdata/CMakeFiles/nastran_blockdata.dir/build
.PHONY : nastran_blockdata/fast

#=============================================================================
# Target rules for targets named nastran_legacy

# Build rule for target.
nastran_legacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran_legacy
.PHONY : nastran_legacy

# fast build rule for target.
nastran_legacy/fast:
	$(MAKE) $(MAKESILENT) -f src/legacy/CMakeFiles/nastran_legacy.dir/build.make src/legacy/CMakeFiles/nastran_legacy.dir/build
.PHONY : nastran_legacy/fast

#=============================================================================
# Target rules for targets named nastran

# Build rule for target.
nastran: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nastran
.PHONY : nastran

# fast build rule for target.
nastran/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/nastran.dir/build.make bin/CMakeFiles/nastran.dir/build
.PHONY : nastran/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... nastran"
	@echo "... nastran_algorithms"
	@echo "... nastran_analysis_dynamic"
	@echo "... nastran_analysis_modal"
	@echo "... nastran_analysis_static"
	@echo "... nastran_blockdata"
	@echo "... nastran_common"
	@echo "... nastran_core_solvers"
	@echo "... nastran_database"
	@echo "... nastran_elements_aero"
	@echo "... nastran_elements_beam"
	@echo "... nastran_elements_shell"
	@echo "... nastran_elements_solid"
	@echo "... nastran_helpers"
	@echo "... nastran_io"
	@echo "... nastran_legacy"
	@echo "... nastran_matrices"
	@echo "... nastran_output"
	@echo "... nastran_parser"
	@echo "... nastran_platform"
	@echo "... nastran_solvers_backends"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

